@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": false,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": false,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 999,
    "backwardDepth": 0,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": false,
    "hideInterfaceCalls": false, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "eapli.ecourse.app.backoffice.console.presentation.course.CreateCourseUI",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1911013184 { 
   	label=ecourse
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1386234867 { 
   	label=app
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   CreateCourseUI375150821[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CreateCourseUI</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   controller: CreateCourseController [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># doShow(): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ headline(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_489743759 { 
   	label=persistence
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   InMemoryCourseRepository650943782[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)InMemoryCourseRepository</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

JpaCourseRepository1852613913[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)JpaCourseRepository</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_861892108 { 
   	label=coursemanagement
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   CourseBuilder1854509879[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CourseBuilder</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   description: Description [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   enrollLimit: EnrollLimit [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   name: Name [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ build(): Course</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CourseRepository816628141[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)CourseRepository</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

CreateCourseController427251605[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CreateCourseController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   authz: AuthorizationService [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   courseRepository: CourseRepository [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ createCourse(name: String, description: String): Course</TD></TR>
<TR><TD ALIGN="LEFT" >+ createCourse(name: String, description: String, minEnroll: Integer, maxEnroll: Integer): Course</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Description1854509879[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Description</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   description: String [1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

EnrollLimit1854509879[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)EnrollLimit</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   maxEnroll: Integer [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   minEnroll: Integer [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Name1854509879[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Name</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   name: String [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ compareTo(o: Name): int</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
CourseBuilder1854509879 -> Description1854509879[label="description
[1]"];
CourseBuilder1854509879 -> EnrollLimit1854509879[label="enrollLimit
[0..1]"];
CourseBuilder1854509879 -> Name1854509879[label="name
[1]"];
CourseRepository816628141 -> InMemoryCourseRepository650943782[arrowhead=none, arrowtail=empty, dir=both];
CourseRepository816628141 -> JpaCourseRepository1852613913[arrowhead=none, arrowtail=empty, dir=both];
CreateCourseController427251605 -> CourseBuilder1854509879[label="createCourse() -> build()"];
CreateCourseController427251605 -> CourseRepository816628141[label="courseRepository
[1]"];
CreateCourseUI375150821 -> CreateCourseController427251605[label="controller
[1]"];
    
}
@enduml