@startuml
hide methods
left to right direction
skinparam classAttributeIconSize 0
skinparam classFontColor automatic
skinparam classHeaderBackgroundColor #4

'//--//--//--//--//--/ User /--//--//--//--//--//--//

package "User Aggregate"     <<Rectangle>> {

    Entity User <<Root>> {
        password
    }

    Object email <<Identity>> {
    }

    Object designation {
        fullName
        shortName
    }

    Entity Teacher {
    }

    Object acronym <<Identity>>{
    }

    Entity Student {
    }

    Object mechanographicNumber <<Identity>>{
    }

    Entity Manager {
    }

    Object personaInformation {
        birthdate
        taxNumber
    }

}

'//--//--//--//--//--/ Exam /--//--//--//--//--//--//

package "Exam Aggregate" <<Rectangle>> {

    Entity Exam <<Root>> {
        description
        openDate
        closeDate
    }

    Object title <<Identity>>{
    }

    Object Question {
        question
        solution
    }

    Object Feedback {
    }

    Entity ExamSubmission {
    grade
    }

    Object QuestionAnswer {
    }

}


'//--//--//--//--//--/ Board /--//--//--//--//--//--//
package "Board Aggregate" <<Rectangle>> {
    Entity Board
    {
        title
        permissions_write
        permissions_read
        archived
    }

    Entity Column
    {
        id
        title
    }

    Entity Row
    {
        id
        title
    }

    Entity Post
    {
        title
    '    author
        timestamp
    }

    Entity Content
    {
        content
    }
}

'//--//--//--//--//--/ Meeting /--//--//--//--//--//--//
package "Meeting Aggregate" <<Rectangle>> {
    Entity Meeting
    {
        schedule
        duration
    }
    Entity MeetingInvitation {
    response
    }


}
'//--//--//--//--//--/ Course /--//--//--//--//--//--//
package "Course Aggregate" <<Rectangle>> {

Entity Course
{
    id
    name
    boolean open //A course may be open or closed
    desc
    maxEnroll
    minEnroll
}

Entity Class
{
    schedule
    duration
}

Entity ExtraClass
{
    schedule
    duration
}


'Entity EnrollmentRequest
'{
'    response
'}

Object EnrolledStudents {
}

Object TeacherCourse{
}

Object Participant {
}

}

'//--//--//

'//--//--//--//--//--/ User /--//--//--//--//--//--//

    User "1" <-- "1" Teacher
    User "1" <-- "1" Student
    User "1" <-- "1" Manager
    Teacher -l-> acronym
    Student -l-> mechanographicNumber
    User -l-> email


    Teacher "1" ---> "1" designation
    Student "1" ---> "1" designation
    Teacher "1" ---> "1" personaInformation
    Student "1" ---> "1" personaInformation

'//--//--//--//--//--/ Exam /--//--//--//--//--//--//

    Exam "1" --> "1..*" Question
    Exam "1" <-l- "0..*" ExamSubmission
    Student "1" <---- "1" ExamSubmission : of a
    QuestionAnswer "1"<--"1" Feedback
    ExamSubmission "1"<--"1..*" QuestionAnswer
    Exam "*" -> "1" Course : of a
    Exam "1" --> "1" title

'//--//--//--//--//--/ Board /--//--//--//--//--//--//

    User "1" -u---> "*" Board : creates
    Board "1" ----> "*" Column : has
    Board "1" ----> "*" Row : has
    Board "1" -> "*" Post : has
    Post "*" ----> "1" Column : is in
    Post "*" ----> "1" Row : is in
    User "1" --> "*" Post : creates
    Post "1" --> "0..1" Content : has

'//--//--//--//--//--/ Meeting /--//--//--//--//--//--//

    User "*" -u---> "1" MeetingInvitation
    MeetingInvitation "*" -r-> "1" Meeting

'//--//--//--//--//--/ Course /--//--//--//--//--//--//

    Class "*" --> "1" Course : of a
    ExtraClass "*" ---> "1" Course : of a
    'EnrollmentRequest "*" --> "*" Course
    'Student "1" -> "1" EnrollmentRequest
    'Student "*" -> "1" ExtraClass : attends
    Teacher "1" -> "*" Class : schedules
    Teacher "1" -> "*" ExtraClass : schedules
    Teacher "1" -> "*" TeacherCourse
    EnrolledStudents "1" --> "*" Course : enrolled in
    EnrolledStudents "1" --> "*" ExtraClass : attend

    Student -> EnrolledStudents : is


    'O que falta: entre student / enrolledstudents e classes/extra classes por uma classe participants, como o stor tinha dito, tal como por valueof das coisas principais, eliminar também a classe enrollmentrequest
@enduml