@startuml
hide methods
left to right direction
skinparam classAttributeIconSize 0
skinparam classFontColor automatic
skinparam classHeaderBackgroundColor #4

'//--//--//--//--//--/ User /--//--//--//--//--//--//

package "User Aggregate" <<Rectangle>> {

    Entity User <<Root>> {
        email
        password
    }

    Object designation {
        fullName
        shortName
    }

    Entity Teacher {
        acronym
    }

    Entity Student {
        mechanographicNumber
    }

    Entity Manager {
    }

    Object personaInformation {
        birthdate
        taxNumber
    }

    User "1" <-- "1" Teacher
    User "1" <-- "1" Student
    User "1" <-- "1" Manager

    Teacher "1" ---> "1" designation
    Student "1" ---> "1" designation
    Teacher "1" ---> "1" personaInformation
    Student "1" ---> "1" personaInformation
}


'//--//--//--//--//--/ Exam /--//--//--//--//--//--//

package "Exam Aggregate" <<Rectangle>> {

    Entity Exam <<Root>> {
        title
        description
        openDate
        closeDate
    }

    Object Question {
        question
        solution
    }

    Object Feedback {
    }

    Entity ExamSubmission {
    }

    Object QuestionAnswer {
    }

}

    Exam "1" --> "1..*" Question
    Exam "1" <- "0..*" ExamSubmission
    Student "1"--->"1" ExamSubmission : takes
    QuestionAnswer "1"<--"1" Feedback
    ExamSubmission "1"<--"1..*" QuestionAnswer


'//--//--//--//--//--/ Board /--//--//--//--//--//--//
package "Board Aggregate" <<Rectangle>> {
    Entity Board
    {
        title
        permissions_write
        permissions_read
        archived
    }

    'Entity Column
    '{
    '    id
    '    title
    '}
    '
    'Entity Row
    '{
    '    id
    '    title
    '}

    Entity Post
    {
        title
    '    author
        timestamp
    }

    Entity Content
    {
        content
    }
}

    User "1" -> "*" Board : creates
    'Board "1" ----> "*" Column : has
    'Board "1" ----> "*" Row : has
    Board "1" -> "*" Post : has
    'Post "*" ----> "1" Column : is in
    'Post "*" ----> "1" Row : is in
    User "1" --> "*" Post : creates
    Post "1" --> "0..1" Content : has

'//--//--//--//--//--/ Meeting /--//--//--//--//--//--//
package "Meeting Aggregate" <<Rectangle>> {
    Entity Meeting
    {
        schedule
        duration
    }
    Entity MeetingInvitation {
    response
    }


    User "*" --> "1" MeetingInvitation
    MeetingInvitation "*" --> "1" Meeting
}
'//--//--//--//--//--/ Course /--//--//--//--//--//--//
package "Course Aggregate" <<Rectangle>> {
Entity Course
{
    id
    name
    boolean open //A course may be open or closed
    desc
    maxEnroll
    minEnroll
}

Entity Class
{
    schedule
    duration
}

Entity ExtraClass
{
    schedule
    duration
}


Entity EnrollmentRequest
{
    response
}

Object EnrolledStudents {
}

Object TeacherCourse{
}
}

Class "*" --> "1" Course : of a
ExtraClass "*" --> "1" Course : of a
EnrollmentRequest "*" --> "*" Course
Student "1" --> "1" EnrollmentRequest
Student "*" --> "1" Class : attends
Student "*" --> "1" ExtraClass : attends
Teacher "1" --> "*" Class : schedules
Teacher "1" --> "*" ExtraClass : schedules
Teacher "1" --> "*" TeacherCourse
TeacherCourse "1" --> "*" Course : coordinates
'Manager "1" ----> "*" EnrollmentRequest : approves
EnrolledStudents "1" --> "*" Course : enrolled in
EnrolledStudents "1" --> "*" ExtraClass : attend



@enduml