@startuml
hide methods
left to right direction
skinparam classAttributeIconSize 0
skinparam classFontColor automatic
skinparam classHeaderBackgroundColor #4
skinparam packageStyle rectangle


'//--//--//--//--//--/ User /--//--//--//--//--//--//

package "User Aggregate"{

    Entity User <<Root>> {
        password
    }

    Object email <<Identity>> {
    }

    Object designation {
        fullName
        shortName
    }

    Object personaInformation {
        birthdate
        taxNumber
    }

}


package "Teacher Aggregate"{
    Entity Teacher {
        }

    Object acronym <<Identity>>{
    }
}

package "Student Aggregate"{
    Entity Student {
    }

    Object mechanographicNumber <<Identity>>{
    }
}

package "Manager Aggregate"{
    Entity Manager {
    }
}


'//--//--//--//--//--/ Exam /--//--//--//--//--//--//

package "Exam Aggregate" <<Rectangle>> {

    Entity Exam <<Root>> {
        description
        openDate
        closeDate
    }

    Object Title <<Identity>>{
    }

    Object Question {
        question
        solution
    }

    Object Feedback {
    }

    Entity ExamSubmission {
    grade
    }

    Object Answer {
    }

    Object MatchingQuestion {
    }
    Object MultipleChoice{
    }
    Object ShortAnswer{
    }
    Object TrueFalse{
    }
    Object Numerical{
    }
    Object SelectMissing{
    }

}


'//--//--//--//--//--/ Board /--//--//--//--//--//--//
package "Board Aggregate" <<Rectangle>> {
    Entity Board <<Root>>{

    }

    Entity Post
    {
        timestamp
    }

    Object Content {

    }
    Entity Cell
    {
    }

    Object BoardID {
    }

    Object BoardTitle <<Identity>> {
    }

    Object CellTitle <<Identity>> {
    }

}

'//--//--//--//--//--/ Meeting /--//--//--//--//--//--//
package "Meeting Aggregate" <<Rectangle>> {
    Entity Meeting <<Root>>
    {
        schedule
        duration
    }
    Entity MeetingInvitation {
    response
    }

    Object BoardID <<Identity>> {
    }

    Object MeetingID <<Identity>>{
    }
}
'//--//--//--//--//--/ Course /--//--//--//--//--//--//
package "Course Aggregate" <<Rectangle>> {

Entity Course <<Root>>
{
    maxEnroll
    minEnroll
}

Object CourseID <<Identity>>{
}

Object Name {
}

Object CourseState <<enum>> {
}
Object StudentEnrollmentState <<enum>> {
}

Object Description {
}


Object EnrolledStudents {
}

Object EnrolledTeachers{
    isInCharge
}

Object CourseState <<Enum>> {

}

}

package "Class Aggregate" <<Rectangle>> {
    Entity Class
    {
        date
        duration
    }

    Entity ExtraClass
    {
        date
        duration
    }
}

'//--//--//

'//--//--//--//--//--/ User /--//--//--//--//--//--//

    User "1" <-- "1" Teacher
    User "1" <-l- "1" Student
    User "1" <-r- "1" Manager
    Teacher "1" --> "1"acronym
    Student "1" --> "1" mechanographicNumber
    User "1"-->"1" email

    Teacher "1" -l-> "1" designation
    Student "1" --> "1" designation
    Teacher "1" --> "1" personaInformation
    Student "1" --> "1" personaInformation

'//--//--//--//--//--/ Exam /--//--//--//--//--//--//

    Exam "1" --> "1..*" Question : has
    Exam "1" <-- "*" ExamSubmission : of a
    Student "1" <----- "1" ExamSubmission : of a
    Teacher "1" --> "*" Exam : creates
    Answer "1"<--"1" Feedback : of
    ExamSubmission "1"-->"1..*" Answer
    Exam "*" <-- "1" Course : has
    Exam "1" --> "1" Title

    Question "1" --> "1" MatchingQuestion: is
    Question "1" --> "1" MultipleChoice: is
    Question "1" --> "1" ShortAnswer: is
    Question "1" --> "1" TrueFalse: is
    Question "1" --> "1" Numerical: is
    Question "1" --> "1" SelectMissing: is


'//--//--//--//--//--/ Board /--//--//--//--//--//--//

    User "1" -u----> "*" Board : creates
    User "1" --> "*" Post : creates
    Post "1" --> "0..1" Content : has
    Board "1" --> "1..*" Cell : has
    Board "1" --> "1" BoardID
    Board "1" -l-> "1" BoardTitle
    Post "1" --> "*" Cell : is in
    Cell "1" --> "1" CellTitle

    note right of Cell : number of cells must form a rectangle

'//--//--//--//--//--/ Meeting /--//--//--//--//--//--//

    User "1" -u---> "1" MeetingInvitation
    MeetingInvitation "*" <-- "1" Meeting
    Meeting "1"--> "1"MeetingID

'//--//--//--//--//--/ Course /--//--//--//--//--//--//

    Class "*" <--l- "1" Course : has
    ExtraClass "*" <-- "1" Course : has
    Teacher "1" --> "*" Class : schedules
    Teacher "1" --> "*" ExtraClass : schedules
    Teacher "1" --> "*" EnrolledTeachers : is in
    EnrolledTeachers "*" <-- "1" Course : has
    EnrolledStudents "*" <-- "1" Course : has
    Course "1"-r->"1" CourseState
    Course "1" --> "1" CourseID
    Course "1"-->"1" Name
    Course "1"--> "1"Description
    Student "1"--> "1"EnrolledStudents : requests
    EnrolledStudents"1" -r-> "1"StudentEnrollmentState

    note right of EnrolledTeachers : only one teacher is in charge of a course
@enduml