@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": false,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "eapli.ecourse.app.manager.console.presentation.course.ListCourseUI",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1911013184 { 
   	label=ecourse
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1386234867 { 
   	label=app
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   ListCourseUI707486463[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ListCourseUI</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   controller: ListCourseController [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># elementName(): String</TD></TR>
<TR><TD ALIGN="LEFT" ># elementPrinter(): Visitor&lt;Course&gt;</TD></TR>
<TR><TD ALIGN="LEFT" ># elements(): Iterable&lt;Course&gt;</TD></TR>
<TR><TD ALIGN="LEFT" ># emptyMessage(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ headline(): String</TD></TR>
<TR><TD ALIGN="LEFT" ># listHeader(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_489743759 { 
   	label=persistence
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   JpaCourseRepository1852613913[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)JpaCourseRepository</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ findAllCoursesOpenOrEnrollState(): Iterable&lt;Course&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ findAllCoursesWithState(state: State): Iterable&lt;Course&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ findAllCoursesWithoutState(state: State): Iterable&lt;Course&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_861892108 { 
   	label=coursemanagement
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   ListCourseController427251605[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ListCourseController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   service: ListCourseService [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ allCourses(): Iterable&lt;Course&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ListCourseService427251605[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ListCourseService</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   authz: AuthorizationService [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   courseRepository: CourseRepository [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ allClosedCourses(): Iterable&lt;Course&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ allCourses(): Iterable&lt;Course&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ allCoursesOpenOrEnroll(): Iterable&lt;Course&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ allEnrollCourses(): Iterable&lt;Course&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ allNotClosedCourses(): Iterable&lt;Course&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ allNotEnrollCourses(): Iterable&lt;Course&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ allOpenCourses(): Iterable&lt;Course&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ allProgressCourses(): Iterable&lt;Course&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
ListCourseController427251605 -> ListCourseService427251605[label="service
[1]"];
ListCourseService427251605 -> JpaCourseRepository1852613913[arrowhead=none];
ListCourseUI707486463 -> ListCourseController427251605[label="controller
[1]"];
    
}
@enduml