@startuml

Actor Manager as Actor
participant ListCourseUI as ListCourseUI <<presentation>>
participant ListCourseController as ListCourseController <<controller>>
participant ListCourseService as ListCourseService <<service>>
participant CourseRepository as CourseRepository <<repository>>

Actor -> ListCourseUI : ask to see courses
activate ListCourseUI
ListCourseUI -> ListCourseController : allCourses
activate ListCourseController
ListCourseController -> ListCourseService : allCourses
activate ListCourseService
ListCourseService -> CourseRepository : allCourses
activate CourseRepository
Database database
CourseRepository -> database : allCourses
activate database
database --> CourseRepository
deactivate database
CourseRepository --> ListCourseService
deactivate CourseRepository
ListCourseService --> ListCourseController
deactivate ListCourseService
ListCourseController --> ListCourseUI
deactivate ListCourseController
return list courses
@enduml