@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": false,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "eapli.ecourse.app.teacher.console.presentation.course.ListAssignCoursesUI",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1911013184 { 
   	label=ecourse
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1386234867 { 
   	label=app
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   ListAssignCoursesUI1343459916[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ListAssignCoursesUI</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   controller: ListTeacherCoursesController [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># elementName(): String</TD></TR>
<TR><TD ALIGN="LEFT" ># elementPrinter(): Visitor&lt;Course&gt;</TD></TR>
<TR><TD ALIGN="LEFT" ># elements(): Iterable&lt;Course&gt;</TD></TR>
<TR><TD ALIGN="LEFT" ># emptyMessage(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ headline(): String</TD></TR>
<TR><TD ALIGN="LEFT" ># listHeader(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_489743759 { 
   	label=persistence
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   JpaTeacherUserRepository1852613913[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)JpaTeacherUserRepository</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getTeacherUserFromSystemUser(systemUser: SystemUser): TeacherUser</TD></TR>
<TR><TD ALIGN="LEFT" >+ joinAllTeachersWithSystemUser(): Iterable&lt;TeacherUser&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

JpaTeachersInCourseRepository1852613913[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)JpaTeachersInCourseRepository</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ findAllCoursesTeacherIsAssign(acronym: Acronym): Iterable&lt;Course&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_861892108 { 
   	label=coursemanagement
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   ListTeacherCoursesController427251605[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ListTeacherCoursesController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   authz: AuthorizationService [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   teacherUserRepository: TeacherUserRepository [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   teachersInCourseRepository: TeachersInCourseRepository [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ findAllCoursesTeacherIsAssign(): Iterable&lt;Course&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TeachersInCourse1854509879[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TeachersInCourse</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   course: Course [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   id: TeachersInCourseKey [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   isInCharge: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   teacher: TeacherUser [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ course(): Course</TD></TR>
<TR><TD ALIGN="LEFT" >+ identity(): TeachersInCourseKey</TD></TR>
<TR><TD ALIGN="LEFT" >+ sameAs(other: Object): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ teacher(): TeacherUser</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_925774986 { 
   	label=usertypemanagement
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   Acronym1814895075[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Acronym</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   acronym: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ compareTo(o: Acronym): int</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

BirthDate2032408415[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)BirthDate</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   birthDate: Calendar [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TaxPayerNumber2032408415[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TaxPayerNumber</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   taxPayerNumber: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ compareTo(o: TaxPayerNumber): int</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TeacherUser1814895075[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TeacherUser</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   acronym: Acronym [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   birthDate: BirthDate [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   systemUser: SystemUser [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   taxPayerNumber: TaxPayerNumber [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   teachersInCourses: Set&lt;TeachersInCourse&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   version: Long [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ acronym(): Acronym</TD></TR>
<TR><TD ALIGN="LEFT" >+ birthDate(): BirthDate</TD></TR>
<TR><TD ALIGN="LEFT" >+ identity(): Acronym</TD></TR>
<TR><TD ALIGN="LEFT" >+ sameAs(other: Object): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ taxPayerNumber(): TaxPayerNumber</TD></TR>
<TR><TD ALIGN="LEFT" >+ user(): SystemUser</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
ListAssignCoursesUI1343459916 -> ListTeacherCoursesController427251605[label="controller
[0..1]"];
ListTeacherCoursesController427251605 -> JpaTeacherUserRepository1852613913[arrowhead=none];
ListTeacherCoursesController427251605 -> JpaTeachersInCourseRepository1852613913[arrowhead=none];
ListTeacherCoursesController427251605 -> TeacherUser1814895075[label="findAllCoursesTeacherIsAssign() -> acronym()"];
TeacherUser1814895075 -> Acronym1814895075[label="acronym
[0..1]"];
TeacherUser1814895075 -> BirthDate2032408415[label="birthDate
[0..1]"];
TeacherUser1814895075 -> TaxPayerNumber2032408415[label="taxPayerNumber
[0..1]"];
TeacherUser1814895075 -> TeachersInCourse1854509879[label="teachersInCourses
[0..*]"];
    
}
@enduml